language: node_js

node_js:
  - lts/*
  - node

services:
  - docker

cache: npm

install:
  - npm ci

before_script:
  - npm run bootstrap

script:
  - npm run lint
  - make gen/ts
  - lerna run build
