name: Install Node.js dependencies

inputs:
  node-version:
    description: Node.js version
    required: true
    default: 18.x

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.1.1
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: https://registry.npmjs.org
    - name: Install dependencies
      run: pnpm install
