---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
spec:
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      description: A sealed (encrypted) Secret
      properties:
        apiVersion:
          type: string
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
        kind:
          type: string
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
        metadata:
          type: object
        spec:
          type: object
          description: SealedSecretSpec is the specification of a SealedSecret
          properties:
            data:
              type: object
              deprecated: true
              description: Data is deprecated and will be removed eventually. 
                Use per-value EncryptedData instead.
            encryptedData:
              type: object
              description: Template defines the structure of the Secret that 
                will be created from this sealed secret.
            template:
              type: object
              description: SecretTemplateSpec describes the structure a Secret 
                should have when created from a template. Template defines the 
                structure of the Secret that will be created from this sealed secret.
              properties:
                metadata:
                  type: object
                  description: Standard object's metadata.
                type:
                  description: Used to facilitate programmatic handling of secret data.
  version: v1alpha1