apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterimportconfigs.net.gke.io
spec:
  conversion:
    strategy: None
  group: net.gke.io
  names:
    kind: ClusterImportConfig
    listKind: ClusterImportConfigList
    plural: clusterimportconfigs
    singular: clusterimportconfig
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                clusteripranges:
                  items:
                    properties:
                      cidrs:
                        items:
                          type: string
                        type: array
                      cluster:
                        type: string
                    type: object
                  type: array
                networks:
                  items:
                    type: string
                  type: array
                zones:
                  items:
                    type: string
                  type: array
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
