apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: entitlements.anthos.gke.io
spec:
  conversion:
    strategy: None
  group: anthos.gke.io
  names:
    kind: Entitlement
    listKind: EntitlementList
    plural: entitlements
    singular: entitlement
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Entitlement is a CR representing that Anthos software may be run on
            a particular cluster. This is written to Anthos-enabled clusters by
            a Hub controller. This is read by in-cluster Anthos services
            performing Entitlement checks.
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                expirationTimestamp:
                  description: ExpirationTimestamp is when this Entitlement expires. An RFC3339
                    date/time.
                  format: date-time
                  type: string
              type: object
          required:
            - metadata
          type: object
      served: true
      storage: true
