apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redirectservices.networking.gke.io
spec:
  conversion:
    strategy: None
  group: networking.gke.io
  names:
    kind: RedirectService
    listKind: RedirectServiceList
    plural: redirectservices
    shortNames:
      - rds
    singular: redirectservice
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: GoogleRedirectService describes the specification used by redirect
            services on GKE.
          properties:
            metadata:
              properties:
                name:
                  pattern: ^default$
                  type: string
              type: object
            spec:
              description: Spec is the desired configuration for Google redirect service.
              properties:
                redirect:
                  description: redirect specifies a redirection operation.
                  properties:
                    provider:
                      description: Provider of the original service.
                      enum:
                        - kube-dns
                      minLength: 1
                      type: string
                    type:
                      description: Type of service that needs redirection.
                      enum:
                        - nodelocaldns
                      minLength: 1
                      type: string
                  type: object
              type: object
          type: object
      served: true
      storage: true
