apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceimports.net.gke.io
spec:
  conversion:
    strategy: None
  group: net.gke.io
  names:
    kind: ServiceImport
    listKind: ServiceImportList
    plural: serviceimports
    singular: serviceimport
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The type of this ServiceImport
          jsonPath: .spec.type
          name: Type
          type: string
        - description: The VIP for this ServiceImport
          jsonPath: .spec.ips
          name: IP
          type: string
        - description: The age of the ServiceImport
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                ips:
                  items:
                    type: string
                  maxItems: 1
                  type: array
                ports:
                  items:
                    properties:
                      appProtocol:
                        type: string
                      name:
                        type: string
                      port:
                        format: int32
                        type: integer
                      protocol:
                        type: string
                    required:
                      - port
                    type: object
                  type: array
                sessionAffinity:
                  type: string
                sessionAffinityConfig:
                  properties:
                    clientIP:
                      properties:
                        timeoutSeconds:
                          format: int32
                          type: integer
                      type: object
                  type: object
                type:
                  type: string
              required:
                - ports
                - type
              type: object
            status:
              properties:
                clusters:
                  items:
                    properties:
                      cluster:
                        type: string
                    required:
                      - cluster
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
