apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceimportconfigs.net.gke.io
spec:
  conversion:
    strategy: None
  group: net.gke.io
  names:
    kind: ServiceImportConfig
    listKind: ServiceImportConfigList
    plural: serviceimportconfigs
    singular: serviceimportconfig
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                clusters:
                  items:
                    properties:
                      capacityScaler:
                        type: string
                      maxEatePerEndpoint:
                        type: string
                      maxrate:
                        type: string
                      membershipName:
                        type: string
                      neg:
                        type: string
                    type: object
                  type: array
                negs:
                  items:
                    type: string
                  type: array
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
