apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: updateinfos.nodemanagement.gke.io
spec:
  conversion:
    strategy: None
  group: nodemanagement.gke.io
  names:
    kind: UpdateInfo
    listKind: UpdateInfoList
    plural: updateinfos
    shortNames:
      - updinf
    singular: updateinfo
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                Type:
                  type: string
                instanceGroupUrl:
                  type: string
                surgeNode:
                  type: string
                targetNode:
                  type: string
                validUntil:
                  format: date-time
                  type: string
              type: object
          type: object
      served: true
      storage: true
