name: Test
on:
  push:
  pull_request:

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  PNPM_VERSION: 6.11.5

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Set pnpm store dir
        run: pnpm config set store-dir ${{ env.PNPM_CACHE_FOLDER }}
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm run build
      - name: Lint files
        run: pnpm run lint
  test:
    runs-on: ubuntu-20.04
    needs:
      - lint
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Set pnpm store dir
        run: pnpm config set store-dir ${{ env.PNPM_CACHE_FOLDER }}
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm run build
      - name: Run unit tests
        run: pnpm run test -- --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
